local ADDON, NS = ...
NS.L = NS.L or {}
local L = NS.L

L["ADDON_NAME"]                     = "HomeDecor"
L["SETTINGS"]                       = "Settings"
L["COMMUNITY"]                      = "Community"
L["WHATS_NEW"]                      = "What's New"
L["SEARCH_PLACEHOLDER"]             = "Search..."
L["LINK"]                           = "Link"
L["RESET"]                          = "Reset"
L["RESET_ALL_FILTERS"]              = "Reset All Filters"
L["FILTERS"]                        = "Filters"
L["SAVED_ITEMS"]                    = "Saved Items"
L["EVENTS"]                         = "Events"
L["TRACKERS"]                       = "Trackers"
L["DECOR_TRACKER"]                  = "Decor Tracker"
L["LUMBER_TRACKER"]                 = "Lumber Tracker"
L["TRACKER"]                        = "Tracker"
L["SCALE"]                          = "Scale"
L["SIZE"]                           = "Size"
L["TRANSPARENCY"]                   = "Transparency"
L["TRANSPARENCY_COLON"]             = "Transparency:"
L["PANEL_TRANSPARENCY"]             = "Panel Transparency"
L["WAYPOINT"]                       = "Waypoint"
L["SUPPORT_DISCORD"]                = "Support Discord:"
L["AUTO_OPEN"]                      = "Auto Open"

L["NO_ITEMS_FOUND"]                 = "No items found"
L["NO_VENDORS"]                     = "No vendors"
L["NO_ACTIVE_EVENTS"]               = "No active events"
L["ALL_COLLECTED"]                  = "All collected"
L["COLLECTED"]                      = "Collected"

L["VENDOR"]                         = "Vendor"
L["VENDORS"]                        = "Vendors"
L["VENDOR_SUFFIX"]                  = " Vendors"
L["VENDOR_OPTIONS"]                 = "Vendor Options"
L["REPUTATION"]                     = "Reputation"
L["CURRENCY"]                       = "Currency"
L["QUESTS_ACHS"]                    = "Quests / Achs"
L["FACTION"]                        = "Faction"
L["ZONE"]                           = "Zone"
L["DROPS_FROM"]                     = "Drops From:"
L["TAG_ACHIEVEMENT"]                = "[Achievement]"
L["TAG_DROP"]                       = "[Drop]"
L["TAG_PROFESSION"]                 = "[Profession]"
L["TAG_PVP"]                        = "[PvP]"
L["TAG_QUEST"]                      = "[Quest]"
L["TAG_VENDOR_ITEM"]                = "[Vendor Item]"
L["DYEABLE"]                        = "Dyeable"
L["REQUIRES"]                       = "Requires"
L["CLASS_HALL"]                     = "Class Hall"
L["VENDOR_TRACKER"]                 = "Vendor Tracker"
L["ALL"]                            = "All"
L["ACHIEVEMENTS"]                   = "Achievements"
L["DROPS"]                          = "Drops"
L["PROFESSIONS"]                    = "Professions"
L["PVP"]                            = "PvP"
L["QUESTS"]                         = "Quests"
L["UNCATEGORIZED"]                  = "Uncategorized"
L["CATEGORY"]                       = "Category"
L["SUBCATEGORY"]                    = "Subcategory"
L["EXPANSION"]                      = "Expansion"
L["ALL_CATEGORIES"]                 = "All Categories"
L["ALL_SUBCATEGORIES"]              = "All Subcategories"
L["ALL_EXPANSIONS"]                 = "All Expansions"
L["ALL_ZONES"]                      = "All Zones"
L["ALL_FACTIONS"]                   = "All Factions"
L["COMPLETED"]                      = "Completed"

L["ITEM_PREFIX"]                    = "Item "
L["DECOR_PREFIX"]                   = "Decor "
L["VENDOR_PREFIX"]                  = "Vendor "
L["QUEST_PREFIX"]                   = "Quest "
L["ACHIEVEMENT_PREFIX"]             = "Achievement "

L["HINT_VIEW_ITEM"]                 = "Left Click: View Item"
L["HINT_EXPAND_COLLAPSE"]           = "Left Click: Expand/Collapse"
L["HINT_VENDOR_LOCATION"]           = "Right Click: Vendor Location"
L["HINT_CLICK_WOWHEAD"]            = "Click: Wowhead Link"
L["HINT_ALT_WOWHEAD"]              = "Alt + Click: Wowhead Link"
L["HINT_CTRL_ACHIEVEMENT"]         = "Ctrl + Click: View Achievement"
L["HINT_SHIFT_MISSING"]            = "Hold Shift: show missing"
L["HINT_CLICK_MAP"]                = "Click: Open Map"
L["HINT_CTRL_COPY"]                = "Ctrl+C to copy, then paste into your browser."
L["HINT_CTRL_WOWHEAD"]             = "Use Ctrl+Click to open the correct WoWHead link."
L["TREASURE_HUNT_WARNING"]         = "There are many versions of the Decor Treasure Hunt quest."

L["REQ_REPUTATION"]                 = "Reputation required"
L["REQ_QUEST"]                      = "Quest required"
L["REQ_NONE_QUEST_ACH"]            = "No quest or achievement required"
L["REQ_NONE_REPUTATION"]           = "No reputation required"
L["WOWHEAD_LINKS"]                  = "Wowhead Links"

L["OPT_SUBTITLE"]                   = "Quality-of-life settings for the addon."
L["OPT_SHOW_MINIMAP_BTN"]          = "Show minimap button"
L["OPT_MINIMAP"]                    = "Minimap"
L["OPT_MINIMAP_PINS"]              = "Show vendor pins on the minimap"
L["OPT_WORLD_MAP"]                  = "World Map"
L["OPT_WORLDMAP_PINS"]             = "Show vendor pins on the world map"
L["OPT_HIDE_COLLECTED"]            = "Hide already collected items"
L["OPT_HIDE_COLLECTED_TIP"]        = "Hides items you have already collected from the browser and list views"
L["OPT_PIN_APPEARANCE"]            = "Pin Appearance"
L["OPT_PIN_STYLE"]                  = "Pin Style:"
L["OPT_PIN_HOUSE"]                  = "House Icon"
L["OPT_PIN_DOT"]                    = "Dot"
L["OPT_PIN_COLOR"]                  = "Pin Color"
L["OPT_RESET_COLOR"]               = "Reset Color"
L["OPT_PIN_SIZE"]                   = "Pin Size"
L["OPT_TRACKER_HEADER"]            = "Tracker"
L["OPT_HIGHLIGHT_ZONE"]            = "Highlight saved items when entering zone"
L["OPT_HIGHLIGHT_ZONE_TIP"]        = "When enabled, saved items will be highlighted when you enter a new zone"

L["OPT_VENDOR_SUBTITLE"]           = "Control what HomeDecor overlays on the vendor window."
L["OPT_SHOW_CHECKMARK"]            = "Show collected checkmark"
L["OPT_SHOW_CHECKMARK_TIP"]        = "Show a checkmark on vendor items you already own in your housing storage"
L["OPT_SHOW_OWNED_COUNT"]          = "Show owned count"
L["OPT_SHOW_OWNED_COUNT_TIP"]      = "Show a number on vendor items indicating how many you own in your housing storage"
L["OPT_VENDOR_TOOLTIP"]            = "Show vendor NPC tooltip info"
L["OPT_VENDOR_TOOLTIP_TIP"]        = "Show HomeDecor info in the tooltip when hovering over a vendor NPC"

L["MAP_TRACKER_SETTINGS"]          = "Map & tracker settings"
L["MAP_PINS_HEADER"]               = "Map Pins"
L["MAP_SHOW_MINIMAP"]              = "Show on minimap"
L["MAP_SHOW_WORLDMAP"]             = "Show on world map"
L["MAP_HIDE_COLLECTED"]            = "Hide collected items"
L["MAP_HIDE_COMPLETED_VENDORS"]    = "Hide completed vendors"
L["MAP_PIN_STYLE_HEADER"]          = "Pin Appearance"
L["MAP_STYLE"]                     = "Style"
L["MAP_COLOR"]                     = "Color"
L["MAP_SIZE"]                      = "Size"

L["TRACK_CURRENT_ZONE"]            = "Track Current Zone"
L["HIDE_COMPLETED"]                = "Hide Completed:"
L["HIGHLIGHT_SAVED"]               = "Highlight Saved Items:"

L["FILTER_HIDE_COMPLETED"]         = "Hide Completed"
L["FILTER_ALTS_REP_HINT"]          = "Login to Alts once to update Reputations you have completed"
L["FILTER_ALTS_QUEST_HINT"]        = "Login to Alts once to update quests you've completed on any character"
L["FILTER_ACH_COMPLETED_HINT"]     = "Show only items from achievements you've completed"

L["LUMBER_TOTAL"]                   = "Lumber Total: "
L["LUMBER_TOTAL_ZERO"]             = "Lumber Total: 0"
L["LUMBER_GOAL_AMOUNT"]            = "Goal Amount:"
L["LUMBER_HIGHLIGHT_SAVED"]        = "Highlight Saved Items:"
L["LUMBER_COMPACT_MODE"]           = "Compact Mode"
L["LUMBER_COMPACT_TIP"]            = "Shows a condensed single-line list — fits more items with less screen space"
L["LUMBER_TOGGLE_COMPACT"]         = "Toggle compact single-line view"
L["LUMBER_SHOW_ICONS"]             = "Show Icons"
L["LUMBER_HIDE_ZERO"]              = "Hide Items with 0"
L["LUMBER_ACCOUNT_WIDE"]           = "Account Wide"
L["LUMBER_ACCOUNT_WIDE_TIP"]       = "Combines lumber counts from all characters.\n\nHover over rows to see per-character breakdown."
L["LUMBER_AUTO_CALC_GOALS"]        = "Auto-Calculate Goals"
L["LUMBER_AUTO_CALC_GOALS_TIP"]    = "Automatically calculates goals based on housing decor recipes you haven't crafted yet"
L["LUMBER_AUTO_FARM"]              = "Auto Farm Mode"
L["LUMBER_AUTO_FARM_TIP"]          = "Automatically start farming stats when you loot lumber"
L["LUMBER_FARMING_SETTINGS"]       = "Farming Settings"
L["LUMBER_FARMING_STATS"]          = "Farming Stats"
L["LUMBER_CHARACTER_BREAKDOWN"]    = "Character Breakdown:"
L["LUMBER_WARBAND_BANK"]           = "Warband Bank"
L["LUMBER_BTN_START_FARMING"]      = "START FARMING"
L["LUMBER_BTN_START"]              = "START"
L["LUMBER_BTN_PAUSE"]              = "PAUSE"
L["LUMBER_BTN_RESUME"]             = "RESUME"
L["LUMBER_BTN_RESET"]              = "RESET"
L["LUMBER_STAT_SESSION"]           = "SESSION"
L["LUMBER_STAT_TOTAL"]             = "TOTAL"
L["LUMBER_STAT_BAGS"]              = "BAGS"
L["LUMBER_STAT_COLLECTING"]        = "COLLECTING"

L["LDB_LEFT_CLICK"]                = "Left Click: Open"
L["LDB_RIGHT_CLICK"]               = "Right Click: Options"
L["LDB_TOGGLE_TIP"]                = "Click to toggle HomeDecor"

L["SLASH_HEADER"]                  = "HomeDecor Commands:"
L["SLASH_HD"]                      = "/hd                 - Toggle HomeDecor"
L["SLASH_MINIMAP"]                 = "/hd minimap [show|hide]"
L["SLASH_PINS"]                    = "/hd pins [minimap|worldmap]  - Toggle vendor pins"
L["SLASH_OPTIONS"]                 = "/hd options          - Open options"
L["SLASH_CHANGELOG"]               = "/hd changelog       - Show What's New"

L["JOIN_DISCORD"]                   = "Join our Discord community"
L["SUPPORT_BUYMEACOFFEE"]           = "Support development (BuyMeACoffee)"
L["DONATE_PAYPAL"]                  = "Donate via PayPal"
L["SHARE_HOMEDECOR"]                = "Share HomeDecor with friends"

L["ITEM_LINK"]                      = "Item Link"
L["QUEST_LINK"]                     = "Quest Link"
L["ACHIEVEMENT_LINK"]               = "Achievement Link"

L["VIEW_ICON"]                      = "Icon"
L["VIEW_LIST"]                      = "List"

L["DYEABLE_CLASS"]                  = "Dyeable - "

L["GOAL_MANUAL_PREFIX"]             = "Manual Goal: "
L["GOAL_MANUAL_SUB"]                = "(Set in Settings)"
L["GOAL_AUTO_PREFIX"]               = "Auto Goal: "
L["GOAL_AUTO_SUB"]                  = "Based on housing decor recipes you haven't crafted"
L["GOAL_AUTO_COMPLETE"]             = "All known housing decor using this lumber is complete"

L["EVENT_ITEMS_PLACEHOLDER"]        = "Event items will appear here while active"

L["UNKNOWN"]                        = "Unknown"

L["EXP_CLASSIC"]                    = "Classic"
L["EXP_TBC"]                        = "Burning Crusade"
L["EXP_WOTLK"]                      = "Wrath of the Lich King"
L["EXP_MOP"]                        = "Mists of Pandaria"
L["EXP_WOD"]                        = "Warlords of Draenor"
L["EXP_LEGION"]                     = "Legion"
L["EXP_BFA"]                        = "Battle for Azeroth"
L["EXP_SHADOWLANDS"]                = "Shadowlands"
L["EXP_DRAGONFLIGHT"]               = "Dragonflight"
L["EXP_TWW"]                        = "The War Within"

L["ZONE_EASTERN_KINGDOMS"]          = "Eastern Kingdoms"
L["ZONE_KALIMDOR"]                  = "Kalimdor"
L["ZONE_OUTLAND"]                   = "Outland"
L["ZONE_NORTHREND"]                 = "Northrend"
L["ZONE_THE_MAELSTROM"]             = "The Maelstrom"
L["ZONE_PANDARIA"]                  = "Pandaria"
L["ZONE_DRAENOR"]                   = "Draenor"
L["ZONE_BROKEN_ISLES"]              = "Broken Isles"
L["ZONE_ARGUS"]                     = "Argus"
L["ZONE_ZANDALAR"]                  = "Zandalar"
L["ZONE_KUL_TIRAS"]                 = "Kul Tiras"
L["ZONE_DRAGON_ISLES"]              = "Dragon Isles"
L["ZONE_KHAZ_ALGAR"]                = "Khaz Algar"
L["ZONE_FOUNDERS_POINT"]            = "Founder's Point"
L["ZONE_RAZORSHORE"]                = "Razorshore"

L["ERR_MAPOPUP_FAILED"]             = "HomeDecor: Failed to create MapPopup frame"
L["ERR_MAPOPUPUI_UNAVAILABLE"]      = "HomeDecor: MapPopupUI not available"

L["MORE_ITEMS"]                     = "more..."

L["DECOR_PRICING"]                  = "Decor Pricing"
L["DECOR_AH_CRAFTING_QUEUE"]        = "Crafting Queue"
L["DECOR_AH_CLEAR"]                 = "Clear"
L["DECOR_AH_CLEAR_ALL"]             = "Clear All"
L["DECOR_AH_MATERIALS_SUMMARY"]     = "Materials Summary"
L["DECOR_AH_TOTAL_MATERIALS"]       = "Total Materials:"
L["DECOR_AH_PROFIT_COLON"]          = "Profit:"
L["DECOR_AH_COST_COLON"]            = "Cost:"
L["DECOR_AH_EXPORT_LIST"]           = "Export List"
L["DECOR_AH_EXPORT"]                = "Export"
L["DECOR_AH_IMPORT"]                = "Import"
L["DECOR_AH_AUCTIONATOR"]           = "Auctionator"
L["DECOR_AH_REMOVE"]                = "Remove"
L["DECOR_AH_UNKNOWN_ITEM"]          = "Unknown Item"
L["DECOR_AH_PROFIT_PREFIX"]         = "Profit: "
L["DECOR_AH_LOSS_PREFIX"]           = "Loss: "
L["DECOR_AH_PROFIT_UNKNOWN"]        = "Profit: Unknown"
L["DECOR_AH_EXPORT_SHOPPING_LIST"]  = "Export Shopping List"
L["DECOR_AH_COPY_ALL"]              = "Copy All"
L["DECOR_AH_SALES_TRACKER"]         = "Sales Tracker"
L["DECOR_AH_SALES"]                 = "Sales"
L["DECOR_AH_TODAY"]                 = "Today"
L["DECOR_AH_THIS_WEEK"]             = "This Week"
L["DECOR_AH_SUMMARY_COLON"]         = "Summary:"
L["DECOR_AH_REFRESH"]               = "Refresh"
L["DECOR_AH_CLEAR_DATA"]            = "Clear Data"
L["DECOR_AH_TOTAL_REVENUE"]         = "Total Revenue: "
L["DECOR_AH_EST_PROFIT"]            = "Est. Profit: "
L["DECOR_AH_EST_PROFIT_NA"]         = "Est. Profit: Not available"
L["DECOR_AH_MATERIALS_COLON"]       = "Materials:"
L["DECOR_AH_CLICK_STAR"]            = "Click star to favorite"
L["DECOR_AH_RIGHTCLICK_QUEUE"]      = "Right-click to add to queue"
L["DECOR_AH_USE_PRICES_FROM"]       = "Use prices from:"
L["DECOR_AH_LAST_SCAN"]             = "Last Auctionator Scan"
L["DECOR_AH_CLICK_MARK_SCANNED"]    = "Click to mark you just scanned with Auctionator."
L["DECOR_AH_OPENS_AH"]              = "Opens the Auction House to run a Full Scan."
L["DECOR_AH_INSTALL_TIP"]           = "Install Auctionator for automatic price scanning."
L["DECOR_AH_INSTALL_AUCTIONATOR"]   = "Install Auctionator"
L["DECOR_AH_RUN_FULL_SCAN"]         = "Run Full Scan"
L["DECOR_AH_QUEUE_ZERO"]            = "Queue (0)"
L["DECOR_AH_QUEUE_TIP"]             = "Crafting Queue"
L["DECOR_AH_RIGHTCLICK_ADD_QUEUE"]  = "Right-click items to add to queue"
L["DECOR_AH_VIEW_MATERIALS"]        = "View materials and export shopping list"
L["DECOR_AH_VIEW_SOLD"]             = "View your sold auctions and profits"
L["DECOR_AH_TRACKS_MAIL"]           = "Tracks items sold via mail"
L["DECOR_AH_PROFESSION_COLON"]      = "Profession:"
L["DECOR_AH_EXPANSION_COLON"]       = "Expansion:"
L["DECOR_AH_LUMBER_COLON"]          = "Lumber:"
L["DECOR_AH_SEARCH_COLON"]          = "Search:"
L["DECOR_AH_SCALE"]                 = "Scale"
L["DECOR_AH_CREATE_AUCTIONATOR"]    = "Create Auctionator Shopping List"
L["DECOR_AH_CREATES_SHOPPING_LIST"] = "Creates 'HomeDecor' shopping list with all tradeable materials from queue."
L["DECOR_AH_QUEUE_EMPTY"]           = "Queue is Empty"
L["DECOR_AH_QUEUE_EMPTY_HINT"]      = "Add items from the Viewer tab to start building your crafting queue"
L["DECOR_AH_EXPORT_FORMAT_COLON"]   = "Export Format:"
L["DECOR_AH_CLOSE"]                 = "Close"
L["DECOR_AH_IMPORT_TITLE"]          = "Import Shopping List"
L["DECOR_AH_PASTE_LIST"]            = "Paste TSM/Auctionator shopping list:"
L["DECOR_AH_CANCEL"]                = "Cancel"

L["DECOR_AH_JUST_SCANNED"]          = "Just Scanned"
L["DECOR_AH_SCANNED_MIN_AGO"]       = "Scanned %dm ago"
L["DECOR_AH_SCANNED_HOURS_AGO"]     = "Scanned %dh ago"
L["DECOR_AH_QUEUE_COUNT"]           = "Queue (%d)"

L["DROPS_LABEL"]                    = "Drops"
L["DROPS_FROM_PANEL"]               = "Drops From"

L["MAPPIN_LEFT_CLICK_SET_WP"]       = "Left-click: Set waypoint"
L["MAPPIN_LEFT_CLICK_CLEAR_WP"]     = "Left-click: Clear waypoint"
L["MAPPIN_RIGHT_CLICK_VENDOR_ITEMS"] = "Right-click: Show vendor items"
L["MAPPIN_NPC_ID"]                  = "NPC ID: "
L["MAPPIN_LEFT_CLICK_ZONE_MAP"]     = "Left-click: View zone map"
L["MAPPIN_RIGHT_CLICK_ALL_VENDORS"] = "Right-click: Show all vendors"

L["MAP_POPUP_VENDORS"]              = "Vendors"

L["ALTS_PROFESSIONS"]               = "Alts Professions"
L["ALTS_CLICK_CELL_HINT"]           = "Click any cell to see alts & recipes"
L["ALTS_YOUR_ALTS"]                 = "YOUR ALTS"
L["ALTS_PROFITABLE_RECIPES"]        = "PROFITABLE RECIPES"
L["ALTS_TRAINER_LOCATIONS"]         = "TRAINER LOCATIONS"
L["ALTS_SECTION_LABEL"]             = "Alt Professions"
L["ALTS_NOT_LEARNED"]               = "Not learned on any alt"
L["ALTS_NO_ITEMS_MATCH"]            = "No items match the current filter"
L["ALTS_NO_RECIPES_YET"]           = "No Housing Decor recipes here yet!"
L["ALTS_SHOW"]                      = "SHOW:"
L["ALTS_SORT"]                      = "SORT:"
L["ALTS_MKT"]                       = "Mkt:"
L["ALTS_COST"]                      = "Cost:"
L["ALTS_FIND_TRAINER"]              = "Find Trainer"
L["ALTS_TRAINER_LOCATIONS_TIP"]     = "Trainer Locations"

L["TRACKER_TITLE"]                  = "DecorTracker"

L["LUMBER_FARMING_STATS_TITLE"]     = "Farming Stats"

L["ZONE"]                           = "Zone"

L["FILTER_TAB_FILTERS"]             = "Filters"
L["FILTER_TAB_COMPLETED"]           = "Completed"
L["FILTER_HIDE_COMPLETED_ROW"]      = "Hide Completed"
L["FILTER_REPUTATION_ROW"]          = "Reputation"
L["FILTER_QUESTS_ROW"]              = "Quests"
L["FILTER_ACHIEVEMENT_ROW"]         = "Achievement"

L["FILTER_FACTION_ROW"]             = "Faction"
L["FILTER_EXPANSION_ROW"]           = "Expansion"
L["FILTER_ZONE_ROW"]                = "Zone"
L["FILTER_CATEGORY_ROW"]            = "Category"
L["FILTER_SUBCATEGORY_ROW"]         = "Subcategory"
L["FILTER_ALLIANCE"]                = "Alliance"
L["FILTER_HORDE"]                   = "Horde"

L["MAP_PANEL_MAP_PINS"]             = "Map Pins"
L["MAP_PANEL_VENDOR_TRACKER"]       = "Vendor Tracker"
L["MAP_PANEL_PIN_APPEARANCE"]       = "Pin Appearance"
L["MAP_PANEL_SHOW_WORLDMAP"]        = "Show on world map"
L["MAP_PANEL_SHOW_MINIMAP"]         = "Show on minimap"
L["MAP_PANEL_HIDE_COLLECTED"]       = "Hide collected items"
L["MAP_PANEL_HIDE_COMPLETED_VEND"]  = "Hide completed vendors"
L["MAP_PANEL_STYLE"]                = "Style"
L["MAP_PANEL_COLOR"]                = "Color"

L["LUMBER_SHOW_ICONS_TIP"]          = ""
L["LUMBER_COMPACT_MODE_TIP"]        = "Shows a condensed single-line list — fits more items with less screen space"
L["LUMBER_AUTO_FARM_TIP_LONG"]      = "Automatically start farming stats when you loot lumber"
L["LUMBER_ACCOUNT_WIDE_TIP_LONG"]   = "Combines lumber counts from all characters.\n\nHover over rows to see per-character breakdown."
L["LUMBER_AUTO_CALC_GOALS_TIP_LONG"]= "Automatically calculates goals based on housing decor recipes you haven't crafted yet"

L["CURRENCY_FALLBACK"]              = "Currency"
L["DECOR_HASH_PREFIX"]              = "Decor #"
L["DYEABLE_LABEL"]                  = "Dyeable"
L["DYEABLE_CLASS_LABEL"]            = "Dyeable - "
L["UNCATEGORIZED"]                  = "Uncategorized"
L["NO_ITEMS_MATCH_SEARCH"]          = "No items match your search"
L["NO_ACTIVE_EVENTS_TITLE"]         = "No active events"

L["REQ_REPUTATION_TEXT"]            = "Reputation required"
L["REQ_QUEST_TEXT"]                 = "Quest required"

L["CLASS_HALL_HEADER"]              = "Class Hall"

L["ALTS_FILTER_ALL_ITEMS"]          = "All Items"
L["ALTS_FILTER_WITH_PRICE"]         = "With Price Data"
L["ALTS_FILTER_PROFITABLE"]         = "Profitable Only"
L["ALTS_FILTER_HIGH"]               = "High (>100g)"
L["ALTS_FILTER_MEGA"]               = "Mega (>300g)"
L["ALTS_FILTER_CAN_CRAFT"]          = "Can Craft"
L["ALTS_SORT_PROFIT_HL"]            = "Profit High-Low"
L["ALTS_SORT_PROFIT_LH"]            = "Profit Low-High"
L["ALTS_SORT_MARGIN_HL"]            = "Margin High-Low"
L["ALTS_SORT_NAME_AZ"]              = "Name A-Z"
L["ALTS_KNOWN_ONLY"]                = "Known only"
L["ALTS_ALT_PROFESSIONS"]           = "Alt Professions"
L["ALTS_READY_NOW"]                 = "READY NOW"
L["ALTS_TAB_OPPORTUNITIES"]         = "Opportunities"
L["ALTS_TAB_ITEM_TRACKER"]          = "Item Tracker"
L["ALTS_LEGEND_READY"]              = "Ready"
L["ALTS_LEGEND_FAR"]                = "Far"
L["ALTS_LEGEND_NONE"]               = "None"

L["EVENTS_ENDS_IN"]                 = "Ends in "

L["DECOR_AH_NO_ITEMS_FOUND"]        = "No items found"
L["DECOR_AH_NO_ITEMS_MATCH"]        = "No items match your search"
L["DECOR_AH_KNOWN_ONLY"]            = "Known only"
L["DECOR_AH_ALT_PROFESSIONS"]       = "Alt Professions"
L["DECOR_AH_FORMAT_TEXT"]           = "Text"
L["DECOR_AH_FORMAT_TSM"]            = "TSM"
L["DECOR_AH_FORMAT_AUCTIONATOR"]    = "Auctionator"

L["SALES_CONFIRM_CLEAR"]            = "Clear"
L["SALES_CONFIRM_CANCEL"]           = "Cancel"

L["MAP_POPUP_CLASS_HALL"]           = "Class Hall"

L["LUMBER_WARBAND_BANK_LABEL"]      = "Warband Bank"

L["ALTS_CLOSE_SKL"]                 = "CLOSE (<50 SKL)"
L["ALTS_LEGEND_CLOSE"]              = "Close (<50)"

L["FILTER_ALL"]                     = "All"

L["LUMBER_HIDE_ZERO"]               = "Hide Items with 0"

L["EVENTS_PLACEHOLDER_BODY"]        = "Event items will appear here while active"

L["WAYPOINT"]                       = "Waypoint"

L["UNCATEGORIZED"]                  = "Uncategorized"

L["FILTER_ALTS_REP_HINT"]           = "Login to Alts once to update Reputations you have completed"
L["FILTER_ALTS_QUEST_HINT"]         = "Login to Alts once to update quests you've completed on any character"
L["FILTER_ACH_COMPLETED_HINT"]      = "Show only items from achievements you've completed"

L["ALL_FACTIONS"]                   = "All Factions"
L["ALL_EXPANSIONS"]                 = "All Expansions"
L["ALL_ZONES"]                      = "All Zones"
L["ALL_CATEGORIES"]                 = "All Categories"
L["ALL_SUBCATEGORIES"]              = "All Subcategories"

L["OPT_PIN_HOUSE"]                  = "House Icon"
L["OPT_PIN_DOT"]                    = "Dot"

L["VENDOR"]                         = "Vendor"
L["FACTION"]                        = "Faction"
L["REQUIRES"]                       = "Requires"

L["HINT_EXPAND_COLLAPSE"]           = "Left Click: Expand/Collapse"
L["HINT_VENDOR_LOCATION"]           = "Right Click: Vendor Location"
L["HINT_ALT_WOWHEAD"]               = "Alt + Click: Wowhead Link"
L["HINT_VIEW_ITEM"]                 = "Left Click: View Item"
L["HINT_CTRL_ACHIEVEMENT"]          = "Ctrl + Click: View Achievement"
L["HINT_CLICK_WOWHEAD"]             = "Click: Wowhead Link"

L["LUMBER_SHOW_ICONS"]              = "Show Icons"
L["LUMBER_COMPACT_MODE"]            = "Compact Mode"
L["LUMBER_AUTO_FARM"]               = "Auto Farm Mode"
L["LUMBER_ACCOUNT_WIDE"]            = "Account Wide"
L["LUMBER_AUTO_CALC_GOALS"]         = "Auto-Calculate Goals"

L["PROF_TIP_TITLE"]                = "Professions Tip"
L["PROF_TIP_MESSAGE"]              = "Please make sure to go on all alts that have professions and open the Professions window for the addon to record everything."
L["PROF_TIP_OK"]                   = "Got it!"
