local ADDON, NS = ...
if GetLocale() ~= "frFR" then return end

NS.L = NS.L or {}
local L = NS.L

L["SETTINGS"]                       = "Paramètres"
L["COMMUNITY"]                      = "Communauté"
L["WHATS_NEW"]                      = "Nouveautés"
L["SEARCH_PLACEHOLDER"]             = "Rechercher..."
L["LINK"]                           = "Lien"
L["RESET"]                          = "Réinitialiser"
L["RESET_ALL_FILTERS"]              = "Réinitialiser tous les filtres"
L["FILTERS"]                        = "Filtres"
L["SAVED_ITEMS"]                    = "Objets sauvegardés"
L["EVENTS"]                         = "Événements"
L["TRACKERS"]                       = "Trackers"
L["DECOR_TRACKER"]                  = "Tracker de décoration"
L["LUMBER_TRACKER"]                 = "Tracker de bois"
L["TRACKER"]                        = "Tracker"
L["SCALE"]                          = "Échelle"
L["SIZE"]                           = "Taille"
L["TRANSPARENCY"]                   = "Transparence"
L["TRANSPARENCY_COLON"]             = "Transparence :"
L["PANEL_TRANSPARENCY"]             = "Transparence du panneau"
L["WAYPOINT"]                       = "Point de repère"
L["SUPPORT_DISCORD"]                = "Discord de support :"
L["AUTO_OPEN"]                      = "Ouverture auto"

L["NO_ITEMS_FOUND"]                 = "Aucun objet trouvé"
L["NO_VENDORS"]                     = "Aucun marchand"
L["NO_ACTIVE_EVENTS"]               = "Aucun événement actif"
L["ALL_COLLECTED"]                  = "Tout collecté"
L["COLLECTED"]                      = "Collecté"

L["VENDOR"]                         = "Marchand"
L["VENDORS"]                        = "Marchands"
L["VENDOR_SUFFIX"]                  = " Marchands"
L["VENDOR_OPTIONS"]                 = "Options marchand"
L["REPUTATION"]                     = "Réputation"
L["CURRENCY"]                       = "Monnaie"
L["QUESTS_ACHS"]                    = "Quêtes / Hauts faits"
L["FACTION"]                        = "Faction"
L["ZONE"]                           = "Zone"
L["DROPS_FROM"]                     = "Tombe de :"
L["TAG_ACHIEVEMENT"]                = "[Haut fait]"
L["TAG_DROP"]                       = "[Butin]"
L["TAG_PROFESSION"]                 = "[Profession]"
L["TAG_PVP"]                        = "[JcJ]"
L["TAG_QUEST"]                      = "[Quête]"
L["TAG_VENDOR_ITEM"]                = "[Article marchand]"
L["DYEABLE"]                        = "Teignable"
L["REQUIRES"]                       = "Requiert"
L["CLASS_HALL"]                     = "Sanctuaire de classe"
L["VENDOR_TRACKER"]                 = "Tracker de marchands"
L["ALL"]                            = "Tout"
L["ACHIEVEMENTS"]                   = "Hauts faits"
L["DROPS"]                          = "Butins"
L["PROFESSIONS"]                    = "Professions"
L["PVP"]                            = "JcJ"
L["QUESTS"]                         = "Quêtes"
L["UNCATEGORIZED"]                  = "Non catégorisé"
L["CATEGORY"]                       = "Catégorie"
L["SUBCATEGORY"]                    = "Sous-catégorie"
L["EXPANSION"]                      = "Extension"
L["ALL_CATEGORIES"]                 = "Toutes les catégories"
L["ALL_SUBCATEGORIES"]              = "Toutes les sous-catégories"
L["ALL_EXPANSIONS"]                 = "Toutes les extensions"
L["ALL_ZONES"]                      = "Toutes les zones"
L["ALL_FACTIONS"]                   = "Toutes les factions"
L["COMPLETED"]                      = "Terminé"

L["ITEM_PREFIX"]                    = "Objet "
L["DECOR_PREFIX"]                   = "Décor "
L["VENDOR_PREFIX"]                  = "Marchand "
L["QUEST_PREFIX"]                   = "Quête "
L["ACHIEVEMENT_PREFIX"]             = "Haut fait "

L["HINT_VIEW_ITEM"]                 = "Clic gauche : Voir l'objet"
L["HINT_EXPAND_COLLAPSE"]           = "Clic gauche : Développer/Réduire"
L["HINT_VENDOR_LOCATION"]           = "Clic droit : Localisation du marchand"
L["HINT_CLICK_WOWHEAD"]            = "Clic : Lien Wowhead"
L["HINT_ALT_WOWHEAD"]              = "Alt + Clic : Lien Wowhead"
L["HINT_CTRL_ACHIEVEMENT"]         = "Ctrl + Clic : Voir le haut fait"
L["HINT_SHIFT_MISSING"]            = "Maj : afficher les manquants"
L["HINT_CLICK_MAP"]                = "Clic : Ouvrir la carte"
L["HINT_CTRL_COPY"]                = "Ctrl+C pour copier, puis coller dans votre navigateur."
L["HINT_CTRL_WOWHEAD"]             = "Utilisez Ctrl+Clic pour ouvrir le bon lien WoWHead."
L["TREASURE_HUNT_WARNING"]         = "Il existe de nombreuses versions de la quête Chasse au trésor de déco."

L["REQ_REPUTATION"]                 = "Réputation requise"
L["REQ_QUEST"]                      = "Quête requise"
L["REQ_NONE_QUEST_ACH"]            = "Aucune quête ou haut fait requis"
L["REQ_NONE_REPUTATION"]           = "Aucune réputation requise"
L["WOWHEAD_LINKS"]                  = "Liens Wowhead"

L["OPT_SUBTITLE"]                   = "Paramètres de confort pour l'addon."
L["OPT_SHOW_MINIMAP_BTN"]          = "Afficher le bouton de la minicarte"
L["OPT_MINIMAP"]                    = "Minicarte"
L["OPT_MINIMAP_PINS"]              = "Afficher les épingles de marchands sur la minicarte"
L["OPT_WORLD_MAP"]                  = "Carte du monde"
L["OPT_WORLDMAP_PINS"]             = "Afficher les épingles de marchands sur la carte du monde"
L["OPT_HIDE_COLLECTED"]            = "Masquer les objets déjà collectés"
L["OPT_HIDE_COLLECTED_TIP"]        = "Masque les objets déjà collectés dans les vues navigateur et liste"
L["OPT_PIN_APPEARANCE"]            = "Apparence des épingles"
L["OPT_PIN_STYLE"]                  = "Style d'épingle :"
L["OPT_PIN_HOUSE"]                  = "Icône de maison"
L["OPT_PIN_DOT"]                    = "Point"
L["OPT_PIN_COLOR"]                  = "Couleur des épingles"
L["OPT_RESET_COLOR"]               = "Réinitialiser la couleur"
L["OPT_PIN_SIZE"]                   = "Taille des épingles"
L["OPT_TRACKER_HEADER"]            = "Tracker"
L["OPT_HIGHLIGHT_ZONE"]            = "Mettre en évidence les objets sauvegardés en entrant dans la zone"
L["OPT_HIGHLIGHT_ZONE_TIP"]        = "Si activé, les objets sauvegardés seront mis en évidence lors de l'entrée dans une nouvelle zone"

L["OPT_VENDOR_SUBTITLE"]           = "Contrôle ce que HomeDecor affiche en superposition sur la fenêtre du marchand."
L["OPT_SHOW_CHECKMARK"]            = "Afficher la coche collecté"
L["OPT_SHOW_CHECKMARK_TIP"]        = "Affiche une coche sur les articles du marchand déjà possédés dans votre stockage immobilier"
L["OPT_SHOW_OWNED_COUNT"]          = "Afficher le nombre possédé"
L["OPT_SHOW_OWNED_COUNT_TIP"]      = "Affiche un nombre sur les articles du marchand indiquant combien vous en possédez"
L["OPT_VENDOR_TOOLTIP"]            = "Afficher les infos de PNJ marchand dans l'infobulle"
L["OPT_VENDOR_TOOLTIP_TIP"]        = "Affiche les informations HomeDecor dans l'infobulle au survol d'un PNJ marchand"

L["MAP_TRACKER_SETTINGS"]          = "Paramètres carte et tracker"
L["MAP_PINS_HEADER"]               = "Épingles de carte"
L["MAP_SHOW_MINIMAP"]              = "Afficher sur la minicarte"
L["MAP_SHOW_WORLDMAP"]             = "Afficher sur la carte du monde"
L["MAP_HIDE_COLLECTED"]            = "Masquer les objets collectés"
L["MAP_HIDE_COMPLETED_VENDORS"]    = "Masquer les marchands terminés"
L["MAP_PIN_STYLE_HEADER"]          = "Apparence des épingles"
L["MAP_STYLE"]                     = "Style"
L["MAP_COLOR"]                     = "Couleur"
L["MAP_SIZE"]                      = "Taille"

L["TRACK_CURRENT_ZONE"]            = "Suivre la zone actuelle"
L["HIDE_COMPLETED"]                = "Masquer terminés :"
L["HIGHLIGHT_SAVED"]               = "Mettre en évidence les sauvegardés :"

L["FILTER_HIDE_COMPLETED"]         = "Masquer les terminés"
L["FILTER_ALTS_REP_HINT"]          = "Connectez-vous à vos alts une fois pour mettre à jour les réputations complétées"
L["FILTER_ALTS_QUEST_HINT"]        = "Connectez-vous à vos alts une fois pour mettre à jour les quêtes terminées sur n'importe quel personnage"
L["FILTER_ACH_COMPLETED_HINT"]     = "Afficher uniquement les objets issus de hauts faits que vous avez terminés"

L["LUMBER_TOTAL"]                   = "Bois total : "
L["LUMBER_TOTAL_ZERO"]             = "Bois total : 0"
L["LUMBER_GOAL_AMOUNT"]            = "Objectif :"
L["LUMBER_HIGHLIGHT_SAVED"]        = "Mettre en évidence les sauvegardés :"
L["LUMBER_COMPACT_MODE"]           = "Mode compact"
L["LUMBER_COMPACT_TIP"]            = "Affiche une liste condensée sur une seule ligne — plus d'éléments en moins d'espace"
L["LUMBER_TOGGLE_COMPACT"]         = "Basculer vers la vue compacte monoligne"
L["LUMBER_SHOW_ICONS"]             = "Afficher les icônes"
L["LUMBER_HIDE_ZERO"]              = "Masquer les éléments à 0"
L["LUMBER_ACCOUNT_WIDE"]           = "Compte complet"
L["LUMBER_ACCOUNT_WIDE_TIP"]       = "Combine les quantités de bois de tous les personnages.\n\nSurvol d'une ligne pour voir le détail par personnage."
L["LUMBER_AUTO_CALC_GOALS"]        = "Calculer les objectifs automatiquement"
L["LUMBER_AUTO_CALC_GOALS_TIP"]    = "Calcule automatiquement les objectifs en fonction des recettes de décoration que vous n'avez pas encore fabriquées"
L["LUMBER_AUTO_FARM"]              = "Mode farm automatique"
L["LUMBER_AUTO_FARM_TIP"]          = "Démarre automatiquement les stats de farm quand vous looter du bois"
L["LUMBER_FARMING_SETTINGS"]       = "Paramètres de farm"
L["LUMBER_FARMING_STATS"]          = "Statistiques de farm"
L["LUMBER_CHARACTER_BREAKDOWN"]    = "Détail par personnage :"
L["LUMBER_WARBAND_BANK"]           = "Banque de la troupe"
L["LUMBER_BTN_START_FARMING"]      = "COMMENCER LE FARM"
L["LUMBER_BTN_START"]              = "DÉMARRER"
L["LUMBER_BTN_PAUSE"]              = "PAUSE"
L["LUMBER_BTN_RESUME"]             = "REPRENDRE"
L["LUMBER_BTN_RESET"]              = "RÉINITIALISER"
L["LUMBER_STAT_SESSION"]           = "SESSION"
L["LUMBER_STAT_TOTAL"]             = "TOTAL"
L["LUMBER_STAT_BAGS"]              = "SACS"
L["LUMBER_STAT_COLLECTING"]        = "COLLECTE"

L["LDB_LEFT_CLICK"]                = "Clic gauche : Ouvrir"
L["LDB_RIGHT_CLICK"]               = "Clic droit : Paramètres"
L["LDB_TOGGLE_TIP"]                = "Cliquez pour afficher/masquer HomeDecor"

L["SLASH_HEADER"]                  = "Commandes HomeDecor :"
L["SLASH_HD"]                      = "/hd                 - Afficher/masquer HomeDecor"
L["SLASH_MINIMAP"]                 = "/hd minimap [show|hide]"
L["SLASH_PINS"]                    = "/hd pins [minimap|worldmap]  - Activer/désactiver les épingles marchands"
L["SLASH_OPTIONS"]                 = "/hd options          - Ouvrir les paramètres"
L["SLASH_CHANGELOG"]               = "/hd changelog       - Afficher les nouveautés"

L["JOIN_DISCORD"]                   = "Rejoignez notre communauté Discord"
L["SUPPORT_BUYMEACOFFEE"]           = "Soutenir le développement (BuyMeACoffee)"
L["DONATE_PAYPAL"]                  = "Faire un don via PayPal"
L["SHARE_HOMEDECOR"]                = "Partager HomeDecor avec des amis"

L["ITEM_LINK"]                      = "Lien de l'objet"
L["QUEST_LINK"]                     = "Lien de la quête"
L["ACHIEVEMENT_LINK"]               = "Lien du haut fait"

L["VIEW_ICON"]                      = "Icône"
L["VIEW_LIST"]                      = "Liste"

L["DYEABLE_CLASS"]                  = "Teignable - "

L["GOAL_MANUAL_PREFIX"]             = "Objectif manuel : "
L["GOAL_MANUAL_SUB"]                = "(Défini dans les paramètres)"
L["GOAL_AUTO_PREFIX"]               = "Objectif auto : "
L["GOAL_AUTO_SUB"]                  = "Basé sur les recettes de décoration non encore fabriquées"
L["GOAL_AUTO_COMPLETE"]             = "Toute la décoration connue utilisant ce bois est complète"

L["EVENT_ITEMS_PLACEHOLDER"]        = "Les objets d'événement apparaîtront ici lorsqu'ils seront actifs"

L["UNKNOWN"]                        = "Inconnu"

L["EXP_CLASSIC"]                    = "Classique"
L["EXP_TBC"]                        = "La Croisade écarlate"
L["EXP_WOTLK"]                      = "La Colère du Roi-Liche"
L["EXP_MOP"]                        = "Pandaria"
L["EXP_WOD"]                        = "Seigneurs de guerre de Draenor"
L["EXP_LEGION"]                     = "Légion"
L["EXP_BFA"]                        = "La Bataille d'Azeroth"
L["EXP_SHADOWLANDS"]                = "Terres de l'Ombre"
L["EXP_DRAGONFLIGHT"]               = "Dragonflight"
L["EXP_TWW"]                        = "La Guerre au sein"

L["ZONE_EASTERN_KINGDOMS"]          = "Royaumes de l'Est"
L["ZONE_KALIMDOR"]                  = "Kalimdor"
L["ZONE_OUTLAND"]                   = "Outreterre"
L["ZONE_NORTHREND"]                 = "Norfendre"
L["ZONE_THE_MAELSTROM"]             = "Le Maelström"
L["ZONE_PANDARIA"]                  = "Pandaria"
L["ZONE_DRAENOR"]                   = "Draenor"
L["ZONE_BROKEN_ISLES"]              = "Îles Brisées"
L["ZONE_ARGUS"]                     = "Argus"
L["ZONE_ZANDALAR"]                  = "Zandalar"
L["ZONE_KUL_TIRAS"]                 = "Kul Tiras"
L["ZONE_DRAGON_ISLES"]              = "Îles des Dragons"
L["ZONE_KHAZ_ALGAR"]                = "Khaz Algar"
L["ZONE_FOUNDERS_POINT"]            = "Pointe des Fondateurs"
L["ZONE_RAZORSHORE"]                = "Rivage-Tranchant"

L["ERR_MAPOPUP_FAILED"]             = "HomeDecor : Échec de la création du cadre MapPopup"
L["ERR_MAPOPUPUI_UNAVAILABLE"]      = "HomeDecor : MapPopupUI non disponible"

L["MORE_ITEMS"]                     = "de plus..."

L["DECOR_PRICING"]                  = "Prix des décorations"
L["DECOR_AH_CRAFTING_QUEUE"]        = "File d'artisanat"
L["DECOR_AH_CLEAR"]                 = "Effacer"
L["DECOR_AH_CLEAR_ALL"]             = "Tout effacer"
L["DECOR_AH_MATERIALS_SUMMARY"]     = "Résumé des matériaux"
L["DECOR_AH_TOTAL_MATERIALS"]       = "Matériaux totaux :"
L["DECOR_AH_PROFIT_COLON"]          = "Profit :"
L["DECOR_AH_COST_COLON"]            = "Coût :"
L["DECOR_AH_EXPORT_LIST"]           = "Exporter la liste"
L["DECOR_AH_EXPORT"]                = "Exporter"
L["DECOR_AH_IMPORT"]                = "Importer"
L["DECOR_AH_AUCTIONATOR"]           = "Auctionator"
L["DECOR_AH_REMOVE"]                = "Retirer"
L["DECOR_AH_UNKNOWN_ITEM"]          = "Objet inconnu"
L["DECOR_AH_PROFIT_PREFIX"]         = "Profit : "
L["DECOR_AH_LOSS_PREFIX"]           = "Perte : "
L["DECOR_AH_PROFIT_UNKNOWN"]        = "Profit : Inconnu"
L["DECOR_AH_EXPORT_SHOPPING_LIST"]  = "Exporter la liste de courses"
L["DECOR_AH_COPY_ALL"]              = "Tout copier"
L["DECOR_AH_SALES_TRACKER"]         = "Suivi des ventes"
L["DECOR_AH_SALES"]                 = "Ventes"
L["DECOR_AH_TODAY"]                 = "Aujourd'hui"
L["DECOR_AH_THIS_WEEK"]             = "Cette semaine"
L["DECOR_AH_SUMMARY_COLON"]         = "Résumé :"
L["DECOR_AH_REFRESH"]               = "Actualiser"
L["DECOR_AH_CLEAR_DATA"]            = "Effacer les données"
L["DECOR_AH_TOTAL_REVENUE"]         = "Revenus totaux : "
L["DECOR_AH_EST_PROFIT"]            = "Profit estimé : "
L["DECOR_AH_EST_PROFIT_NA"]         = "Profit estimé : Non disponible"
L["DECOR_AH_MATERIALS_COLON"]       = "Matériaux :"
L["DECOR_AH_CLICK_STAR"]            = "Cliquez sur l'étoile pour mettre en favori"
L["DECOR_AH_RIGHTCLICK_QUEUE"]      = "Clic droit pour ajouter à la file"
L["DECOR_AH_USE_PRICES_FROM"]       = "Utiliser les prix de :"
L["DECOR_AH_LAST_SCAN"]             = "Dernier scan Auctionator"
L["DECOR_AH_CLICK_MARK_SCANNED"]    = "Cliquez pour indiquer que vous venez de scanner avec Auctionator."
L["DECOR_AH_OPENS_AH"]              = "Ouvre l'hôtel des ventes pour un scan complet."
L["DECOR_AH_INSTALL_TIP"]           = "Installez Auctionator pour le scan automatique des prix."
L["DECOR_AH_INSTALL_AUCTIONATOR"]   = "Installer Auctionator"
L["DECOR_AH_RUN_FULL_SCAN"]         = "Lancer un scan complet"
L["DECOR_AH_QUEUE_ZERO"]            = "File (0)"
L["DECOR_AH_QUEUE_TIP"]             = "File d'artisanat"
L["DECOR_AH_RIGHTCLICK_ADD_QUEUE"]  = "Clic droit pour ajouter à la file"
L["DECOR_AH_VIEW_MATERIALS"]        = "Voir les matériaux et exporter la liste de courses"
L["DECOR_AH_VIEW_SOLD"]             = "Voir vos enchères vendues et vos profits"
L["DECOR_AH_TRACKS_MAIL"]           = "Suit les objets vendus par courrier"
L["DECOR_AH_PROFESSION_COLON"]      = "Profession :"
L["DECOR_AH_EXPANSION_COLON"]       = "Extension :"
L["DECOR_AH_LUMBER_COLON"]          = "Bois :"
L["DECOR_AH_SEARCH_COLON"]          = "Recherche :"
L["DECOR_AH_SCALE"]                 = "Échelle"
L["DECOR_AH_CREATE_AUCTIONATOR"]    = "Créer une liste de courses Auctionator"
L["DECOR_AH_CREATES_SHOPPING_LIST"] = "Crée la liste de courses 'HomeDecor' avec tous les matériaux échangeables de la file."
L["DECOR_AH_QUEUE_EMPTY"]           = "File vide"
L["DECOR_AH_QUEUE_EMPTY_HINT"]      = "Ajoutez des objets depuis l'onglet Viewer pour commencer à constituer votre file d'artisanat"
L["DECOR_AH_EXPORT_FORMAT_COLON"]   = "Format d'export :"
L["DECOR_AH_CLOSE"]                 = "Fermer"
L["DECOR_AH_IMPORT_TITLE"]          = "Importer une liste de courses"
L["DECOR_AH_PASTE_LIST"]            = "Coller la liste TSM/Auctionator :"
L["DECOR_AH_CANCEL"]                = "Annuler"

L["DECOR_AH_JUST_SCANNED"]          = "Vient d'être scanné"
L["DECOR_AH_SCANNED_MIN_AGO"]       = "Scanné il y a %dm"
L["DECOR_AH_SCANNED_HOURS_AGO"]     = "Scanné il y a %dh"
L["DECOR_AH_QUEUE_COUNT"]           = "File (%d)"

L["DROPS_LABEL"]                    = "Butins"
L["DROPS_FROM_PANEL"]               = "Tombe de"

L["MAPPIN_LEFT_CLICK_SET_WP"]       = "Clic gauche : Définir le point de repère"
L["MAPPIN_LEFT_CLICK_CLEAR_WP"]     = "Clic gauche : Effacer le point de repère"
L["MAPPIN_RIGHT_CLICK_VENDOR_ITEMS"] = "Clic droit : Afficher les articles du marchand"
L["MAPPIN_NPC_ID"]                  = "ID PNJ : "
L["MAPPIN_LEFT_CLICK_ZONE_MAP"]     = "Clic gauche : Voir la carte de zone"
L["MAPPIN_RIGHT_CLICK_ALL_VENDORS"] = "Clic droit : Afficher tous les marchands"

L["MAP_POPUP_VENDORS"]              = "Marchands"

L["ALTS_PROFESSIONS"]               = "Alts - Professions"
L["ALTS_CLICK_CELL_HINT"]           = "Cliquez sur une cellule pour voir les alts & recettes"
L["ALTS_YOUR_ALTS"]                 = "VOS ALTS"
L["ALTS_PROFITABLE_RECIPES"]        = "RECETTES RENTABLES"
L["ALTS_TRAINER_LOCATIONS"]         = "EMPLACEMENTS DES FORMATEURS"
L["ALTS_SECTION_LABEL"]             = "Professions des Alts"
L["ALTS_NOT_LEARNED"]               = "Non appris sur aucun alt"
L["ALTS_NO_ITEMS_MATCH"]            = "Aucun objet ne correspond au filtre actuel"
L["ALTS_NO_RECIPES_YET"]           = "Pas encore de recettes de décoration ici !"
L["ALTS_SHOW"]                      = "AFFICHER :"
L["ALTS_SORT"]                      = "TRIER :"
L["ALTS_MKT"]                       = "Marché :"
L["ALTS_COST"]                      = "Coût :"
L["ALTS_FIND_TRAINER"]              = "Trouver un formateur"
L["ALTS_TRAINER_LOCATIONS_TIP"]     = "Emplacements des formateurs"

L["TRACKER_TITLE"]                  = "Tracker de décoration"

L["LUMBER_FARMING_STATS_TITLE"]     = "Statistiques de farm"

L["ZONE"]                           = "Zone"

L["FILTER_TAB_FILTERS"]             = "Filtres"
L["FILTER_TAB_COMPLETED"]           = "Terminés"
L["FILTER_HIDE_COMPLETED_ROW"]      = "Masquer les terminés"
L["FILTER_REPUTATION_ROW"]          = "Réputation"
L["FILTER_QUESTS_ROW"]              = "Quêtes"
L["FILTER_ACHIEVEMENT_ROW"]         = "Haut fait"

L["FILTER_FACTION_ROW"]             = "Faction"
L["FILTER_EXPANSION_ROW"]           = "Extension"
L["FILTER_ZONE_ROW"]                = "Zone"
L["FILTER_CATEGORY_ROW"]            = "Catégorie"
L["FILTER_SUBCATEGORY_ROW"]         = "Sous-catégorie"
L["FILTER_ALLIANCE"]                = "Alliance"
L["FILTER_HORDE"]                   = "Horde"

L["MAP_PANEL_MAP_PINS"]             = "Épingles de carte"
L["MAP_PANEL_VENDOR_TRACKER"]       = "Tracker de marchands"
L["MAP_PANEL_PIN_APPEARANCE"]       = "Apparence des épingles"
L["MAP_PANEL_SHOW_WORLDMAP"]        = "Afficher sur la carte du monde"
L["MAP_PANEL_SHOW_MINIMAP"]         = "Afficher sur la minicarte"
L["MAP_PANEL_HIDE_COLLECTED"]       = "Masquer les objets collectés"
L["MAP_PANEL_HIDE_COMPLETED_VEND"]  = "Masquer les marchands terminés"
L["MAP_PANEL_STYLE"]                = "Style"
L["MAP_PANEL_COLOR"]                = "Couleur"

L["LUMBER_SHOW_ICONS_TIP"]          = ""
L["LUMBER_COMPACT_MODE_TIP"]        = "Affiche une liste condensée sur une seule ligne — plus d'éléments en moins d'espace"
L["LUMBER_AUTO_FARM_TIP_LONG"]      = "Démarre automatiquement les stats de farm quand vous looter du bois"
L["LUMBER_ACCOUNT_WIDE_TIP_LONG"]   = "Combine les quantités de bois de tous les personnages.\n\nSurvol d'une ligne pour voir le détail par personnage."
L["LUMBER_AUTO_CALC_GOALS_TIP_LONG"]= "Calcule automatiquement les objectifs en fonction des recettes de décoration que vous n'avez pas encore fabriquées"

L["CURRENCY_FALLBACK"]              = "Monnaie"
L["DECOR_HASH_PREFIX"]              = "Décor #"
L["DYEABLE_LABEL"]                  = "Teignable"
L["DYEABLE_CLASS_LABEL"]            = "Teignable - "
L["UNCATEGORIZED"]                  = "Non catégorisé"
L["NO_ITEMS_MATCH_SEARCH"]          = "Aucun objet ne correspond à votre recherche"
L["NO_ACTIVE_EVENTS_TITLE"]         = "Aucun événement actif"

L["REQ_REPUTATION_TEXT"]            = "Réputation requise"
L["REQ_QUEST_TEXT"]                 = "Quête requise"

L["CLASS_HALL_HEADER"]              = "Sanctuaire de classe"

L["ALTS_FILTER_ALL_ITEMS"]          = "Tous les objets"
L["ALTS_FILTER_WITH_PRICE"]         = "Avec données de prix"
L["ALTS_FILTER_PROFITABLE"]         = "Rentable uniquement"
L["ALTS_FILTER_HIGH"]               = "Élevé (>100po)"
L["ALTS_FILTER_MEGA"]               = "Très élevé (>300po)"
L["ALTS_FILTER_CAN_CRAFT"]          = "Peut fabriquer"
L["ALTS_SORT_PROFIT_HL"]            = "Profit haut-bas"
L["ALTS_SORT_PROFIT_LH"]            = "Profit bas-haut"
L["ALTS_SORT_MARGIN_HL"]            = "Marge haut-bas"
L["ALTS_SORT_NAME_AZ"]              = "Nom A-Z"
L["ALTS_KNOWN_ONLY"]                = "Connus uniquement"
L["ALTS_ALT_PROFESSIONS"]           = "Professions des alts"
L["ALTS_READY_NOW"]                 = "PRÊT MAINTENANT"
L["ALTS_TAB_OPPORTUNITIES"]         = "Opportunités"
L["ALTS_TAB_ITEM_TRACKER"]          = "Suivi d'objets"
L["ALTS_LEGEND_READY"]              = "Prêt"
L["ALTS_LEGEND_FAR"]                = "Loin"
L["ALTS_LEGEND_NONE"]               = "Aucun"

L["EVENTS_ENDS_IN"]                 = "Se termine dans "

L["DECOR_AH_NO_ITEMS_FOUND"]        = "Aucun objet trouvé"
L["DECOR_AH_NO_ITEMS_MATCH"]        = "Aucun objet ne correspond à votre recherche"
L["DECOR_AH_KNOWN_ONLY"]            = "Connus uniquement"
L["DECOR_AH_ALT_PROFESSIONS"]       = "Professions des alts"
L["DECOR_AH_FORMAT_TEXT"]           = "Texte"
L["DECOR_AH_FORMAT_TSM"]            = "TSM"
L["DECOR_AH_FORMAT_AUCTIONATOR"]    = "Auctionator"

L["SALES_CONFIRM_CLEAR"]            = "Effacer"
L["SALES_CONFIRM_CANCEL"]           = "Annuler"

L["MAP_POPUP_CLASS_HALL"]           = "Sanctuaire de classe"

L["LUMBER_WARBAND_BANK_LABEL"]      = "Banque de la troupe"

L["ALTS_CLOSE_SKL"]                 = "PROCHE (<50 COMP)"
L["ALTS_LEGEND_CLOSE"]              = "Proche (<50)"

L["FILTER_ALL"]                     = "Tout"

L["LUMBER_HIDE_ZERO"]               = "Masquer les objets à 0"

L["EVENTS_PLACEHOLDER_BODY"]        = "Les objets d'événement apparaîtront ici lorsqu'ils sont actifs"

L["WAYPOINT"]                       = "Point de passage"

L["UNCATEGORIZED"]                  = "Non catégorisé"

L["FILTER_ALTS_REP_HINT"]           = "Connectez-vous à vos alts une fois pour mettre à jour les réputations que vous avez complétées"
L["FILTER_ALTS_QUEST_HINT"]         = "Connectez-vous à vos alts une fois pour mettre à jour les quêtes complétées"
L["FILTER_ACH_COMPLETED_HINT"]      = "Afficher uniquement les objets des hauts faits que vous avez accomplis"

L["ALL_FACTIONS"]                   = "Toutes les factions"
L["ALL_EXPANSIONS"]                 = "Toutes les extensions"
L["ALL_ZONES"]                      = "Toutes les zones"
L["ALL_CATEGORIES"]                 = "Toutes les catégories"
L["ALL_SUBCATEGORIES"]              = "Toutes les sous-catégories"

L["OPT_PIN_HOUSE"]                  = "Icône de maison"
L["OPT_PIN_DOT"]                    = "Point"

L["VENDOR"]                         = "Marchand"
L["FACTION"]                        = "Faction"
L["REQUIRES"]                       = "Requiert"

L["HINT_EXPAND_COLLAPSE"]           = "Clic gauche : Développer/Réduire"
L["HINT_VENDOR_LOCATION"]           = "Clic droit : Localisation du marchand"
L["HINT_ALT_WOWHEAD"]               = "Alt + Clic : Lien Wowhead"
L["HINT_VIEW_ITEM"]                 = "Clic gauche : Voir l'objet"
L["HINT_CTRL_ACHIEVEMENT"]          = "Ctrl + Clic : Voir le haut fait"
L["HINT_CLICK_WOWHEAD"]             = "Clic : Lien Wowhead"

L["LUMBER_SHOW_ICONS"]              = "Afficher les icônes"
L["LUMBER_COMPACT_MODE"]            = "Mode compact"
L["LUMBER_AUTO_FARM"]               = "Mode farm automatique"
L["LUMBER_ACCOUNT_WIDE"]            = "Compte entier"
L["LUMBER_AUTO_CALC_GOALS"]         = "Calcul automatique des objectifs"

L["PROF_TIP_TITLE"]                = "Conseil sur les professions"
L["PROF_TIP_MESSAGE"]              = "Veuillez vous connecter sur tous vos alts ayant des professions et ouvrir la fenêtre des Professions afin que l'addon puisse tout enregistrer."
L["PROF_TIP_OK"]                   = "Compris !"
